# Generated by Django 5.0.6 on 2024-07-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('WorkType', models.CharField(max_length=50)),
                ('Sheet', models.IntegerField()),
                ('Date', models.DateField()),
                ('File', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
