# Generated by Django 5.0.6 on 2024-07-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='Sheet',
            field=models.IntegerField(max_length=255),
        ),
    ]
