# Generated by Django 5.0.6 on 2024-07-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_app', '0002_alter_user_data_sheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='App_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Work', models.CharField(max_length=500)),
                ('Image', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.AlterField(
            model_name='user_data',
            name='Sheet',
            field=models.IntegerField(),
        ),
    ]
