# Generated by Django 5.0.6 on 2024-07-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_app', '0004_alter_app_content_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app_content',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='app_content',
            name='Work',
        ),
        migrations.AddField(
            model_name='app_content',
            name='title',
            field=models.CharField(default='Comming Soon', max_length=100),
        ),
        migrations.AddField(
            model_name='app_content',
            name='image',
            field=models.ImageField(default='None', upload_to='images/'),
        ),
    ]
